### ISSUE TITLE
Connect Four Game

### ISSUE THREAD

**Issue by thejaswin123** [Ayush7614/Bundli-Frontend#110]
# Aim

To build Connect-four game using Javascript, HTML, and CSS.

# Details

Connect Four Game is a multiplayer game where your goal is to connect four dots. The game design simple it only contains a black border and two-color dots(red and blue). The benefit of the project has entertainment and enjoyable moment with your friends, family, classmate, etc.
I would like to work on this project under HCSSoC.
Kindly assign me this issue.
@Ayush7614

**Comment by Ayush7614** [comment]
We have already in the repo
