### ISSUE TITLE
Hangman in JS

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Bundli-Frontend#12]

**Comment by pranjay-poddar** [comment]
Would like to work on adding a hangman to this project, therefore I request you to please assign this task to me.

**Comment by Ayush7614** [comment]
Hello @pranjay-poddar  Thanks For Your Intrest in the Issue You are Participant of HSSOC

**Comment by Ayush7614** [comment]
Go Ahead @pranjay-poddar
