### ISSUE TITLE
Tower_of_Hanoi

### ISSUE THREAD

**Issue by thejaswin123** [Ayush7614/Bundli-Frontend#125]
# Aim
To Build a Tower of Hanoi using HTML, CSS, and Javascript.

# Details

The Tower of Hanoi (also called the Tower of Brahma or Lucas' Tower and sometimes pluralized as Towers) is a mathematical game or puzzle. It consists of three rods and a number of disks of different sizes, which can slide onto any rod. 
I would like to work on this project under HCSSoC.
Kindly assign me this issue.
@Ayush7614

**Comment by Ayush7614** [comment]
We doesnt need this
