### ISSUE TITLE
Google Search Clone In JS

### ISSUE THREAD

**Issue by pranjay-poddar** [Ayush7614/Bundli-Frontend#128]
Google Search clone to run a search query, search images with I'm feeling luck feature and advanced google search feature built with Html, css, and JS.

**Comment by pranjay-poddar** [comment]
Please assign this task to me under HCSSOC.

**Comment by Ayush7614** [comment]
@pranjay-poddar plss give your best in this i accept much more from you in this clone

**Comment by pranjay-poddar** [comment]
@Ayush7614 yeah, I will give my level best. 👍
