### ISSUE TITLE
Real time chat Application with socket.io

### ISSUE THREAD

**Issue by sreyom31** [Ayush7614/Bundli-Frontend#134]
I would like to work on this project as it was listed in ideas. I request you to assign me this project.
@Ayush7614

**Comment by Ayush7614** [comment]
okk @sreyom31 can you plss tell me you are part of any competation or you can only contribute to project

**Comment by sreyom31** [comment]
Yes I am a part of devIncept openSource program. But now i am just starting to contribute in various open source projects, So when i saw the link in the devIncept channel, I thought of starting with this.

**Comment by Ayush7614** [comment]
Ok go ahead @sreyom31
