### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Bundli-Frontend#150]
> ## Description
> Create a Code of Conduct which the Mentors and Participants must abide by.
> 
> ## Additional Details
> * Mention the Standards which everyone should abide by on welcoming and inclusive language including constructive criticism.
> * Add the required responsibilities for Project Maintainers.
> * Mention the Scope of this Code of Conduct.

**Comment by Amrutha1101** [comment]
Can I work in this issue under Devincept'21 from 10th?

**Comment by techabhi08** [comment]
@Ayush7614 can you assign this to me? I would like to work on this issue.

**Comment by Ayush7614** [comment]
@Amrutha1101 go Ahead
