### ISSUE TITLE
Parallax scrolling effect for a website

### ISSUE THREAD

**Issue by aishwaryas15** [Ayush7614/Bundli-Frontend#155]
Using front-end like mainly html,css & javascript I've come up to design a scrolling effect web page.
Here the background content (i.e. an image) is moved at a different speed than the foreground content while scrolling. It looks visually appealing.

**Comment by Ayush7614** [comment]
@aishwaryas15 under which program you can contribute

**Comment by aishwaryas15** [comment]
> @aishwaryas15 under which program you can contribute
I don't get you I guess. It's for a website with some CSS animations & Javascript.

**Comment by Ayush7614** [comment]
Under which open source program you can contribute

**Comment by aishwaryas15** [comment]
> Under which open source program you can contribute

Under DevIncept

**Comment by aditya687** [comment]
Can I work on this issue @Ayush7614 ?

**Comment by Abhicoder03** [comment]
Hi @Ayush7614 I want to contribute in this issue. Can i contribute under hacktoberfest 2021?

**Comment by Ayush7614** [comment]
Go Ahead @Abhicoder03

**Comment by Palaksharma23** [comment]
Hi @Ayush7614 sir i want to work on this issue can you assign it to me ?
