### ISSUE TITLE
Card Hover Effect

### ISSUE THREAD

**Issue by kiruba-r11** [Ayush7614/Bundli-Frontend#166]
**Is your feature request related to a problem? Please describe.**
This is a Card Hover effect, which has a display text, and when hovered it gives more detailed information.

**Describe the solution you'd like**
This is built using HTML, CSS.

**Comment by kiruba-r11** [comment]
@Ayush7614 I would like to work on this as a part of HCSSoC'21

**Comment by kiruba-r11** [comment]
@Ayush7614 can I work on this?

**Comment by techabhi08** [comment]
@Ayush7614 sir I would like to work on this issue. Can you assign this to me please?
