### ISSUE TITLE
JS Calculator with better UI and more features

### ISSUE THREAD

**Issue by kiruba-r11** [Ayush7614/Bundli-Frontend#168]
**Is your feature request related to a problem? Please describe.**

The changes I want to propose to the already existing JS Calculator:
  1. The JS Calculator which is already present doesn't have a delete a single char option, it has only a clear option.
  2. Multiple operands are being added to the input, for eg: 23+- is getting added to the input. Instead, I would give the user an alert to not have multiple operands, and also for other wrong inputs by the user.
  3. The UI needs an update, I would add even dark mode.
  4. The calculator is not responsive, the size is static and even on a larger screen the width of the calculator is equivalent to the mobile size, I would make it responsive.

**Describe the solution you'd like**
It is built using HTML, CSS, JS, and Bootstrap.

**Comment by kiruba-r11** [comment]
@Ayush7614 I would like to work on this as a part of HCSSoC'21

**Comment by Ayush7614** [comment]
What you exactly do if you share screen shot of output then I will assign you

**Comment by kiruba-r11** [comment]
Screenshots:
<table>
  <thead>
    <th>Dark Mode</th>
    <th>Light Mode</th>
  </thead>
  <tbody>
    <tr>
      <td><img width="500" src="https://user-images.githubusercontent.com/76843281/124748595-f10d1700-df40-11eb-8d0d-6a134e37e3b0.png"></td>
       <td><img width="500" src="https://user-images.githubusercontent.com/76843281/124748597-f23e4400-df40-11eb-8041-f72c286f2ae3.png"></td>
    </tr>
  </tbody>
</table>
