### ISSUE TITLE
Update on readme.md file

### ISSUE THREAD

**Issue by PrathmeshMutke** [Ayush7614/Bundli-Frontend#169]
**Is your feature request related to a problem? Please describe.**
I want to add images to languages and framework   section in readme.md file
Please assign me this issue
Devincept 21

**Comment by Ayush7614** [comment]
What you exactly update @PrathmeshMutke

**Comment by PrathmeshMutke** [comment]
I want to add tech stack and framework images in readme file 
For ex. Javascript logo, css logo etc.
I already have made changes in my fork just waited to assign the issue. 
So I can pull request
