### ISSUE TITLE
Added Calcultor in JS

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Bundli-Frontend#2]

**Comment by PadminiRai** [comment]
@Ayush7614 I'd like to work on this issue.

**Comment by kiruba-r11** [comment]
@Ayush7614 Hey, can I work on this.

**Comment by kiruba-r11** [comment]
@Ayush7614 Can I work on this as a part of HCSSoC'21

**Comment by Ayush7614** [comment]
@PadminiRai you can work under which program tell me

**Comment by siddhi-244** [comment]
I want to work on this issue under psoc !

**Comment by PadminiRai** [comment]
> @PadminiRai you can work under which program tell me
@Ayush7614 
Under HCSSoC'21 label. Please and Thank You.

**Comment by PadminiRai** [comment]
@Ayush7614 
**PR** : https://github.com/Ayush7614/Bundli-Frontend/pull/25 fixes this issue . Take a look.
