### ISSUE TITLE
Front-end template for an illustrator

### ISSUE THREAD

**Issue by dilroseR** [Ayush7614/Bundli-Frontend#204]
A simple front end template for an illustrator from which they can use for their own purposes

**Comment by Ayush7614** [comment]
> A simple front end template for an illustrator from which they can use for their own purposes

Under which program you can. Contribute

**Comment by dilroseR** [comment]
> > A simple front end template for an illustrator from which they can use for their own purposes
> 
> Under which program you can. Contribute

I'm a DevIncept Participant
