### ISSUE TITLE
Cloud animation

### ISSUE THREAD

**Issue by abhiramkg2000** [Ayush7614/Bundli-Frontend#213]
# Aim

CSS and JavaScript animation

# Details

using CSS Keyframes animation and JavaScript events created a beautiful scenery

**Comment by abhiramkg2000** [comment]
please assign it to me @Ayush7614

**Comment by Ayush7614** [comment]
@abhiramkg2000 you are participant if DCP or Not

**Comment by Ayush7614** [comment]
and which type of animation you have to make can you explain

**Comment by abhiramkg2000** [comment]
I had contacted you on slack in DevIncept Contribution Program
