### ISSUE TITLE
CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by swathi-469** [Ayush7614/Bundli-Frontend#217]
I would like to add code of conduct for this project please assign this to me

**Comment by swathi-469** [comment]
Yeah shall I start working on it .please assign this to me

**Comment by Ayush7614** [comment]
Plsss mention the Program in which you have to contribute

**Comment by swathi-469** [comment]
I am From DevIncept - Contributions

**Comment by AmruthaCK** [comment]
Issue #150  is the same.

**Comment by Amrutha1101** [comment]
#150  is the same

**Comment by swathi-469** [comment]
Ohh kk I am really sorry for that .. can you  assign issue #150  to me

**Comment by Ayush7614** [comment]
Already we have doesn`t need
