### ISSUE TITLE
Neumorphic Login and Registration Form 

### ISSUE THREAD

**Issue by chandu6111** [Ayush7614/Bundli-Frontend#218]
**Is your feature request related to a problem? Please describe.**
I want to create neumorphic signup and sign-in form both on a single page, with a toggle option.
Users can choose either sign-in or sign-up, and form toggles by the choice and neumorphic effects make the form look professional and appealing.

- [x] DCP`21

**Comment by chandu6111** [comment]
@Ayush7614 could you please assign me this issue?

**Comment by Ayush7614** [comment]
Already we have
