### ISSUE TITLE
Speak-number-guess

### ISSUE THREAD

**Issue by nikhv** [Ayush7614/Bundli-Frontend#226]
# Aim

I want to add speak number guess 

# Details
The Tech stack will be HTML,  CSS, and JS.
We have to speak a number in the microphone and that number will display on the webpage.
I would like to contribute to this issue under the DevIncept program.
please assign this issue to me
@Ayush7614

**Comment by Ayush7614** [comment]
@nikhv what is the status

**Comment by nikhv** [comment]
@Ayush7614 , will make a pr today
