### ISSUE TITLE
Text Slider Animation

### ISSUE THREAD

**Issue by kiruba-r11** [Ayush7614/Bundli-Frontend#230]
**Is your feature request related to a problem? Please describe.**
It is a text slider animation that fills color to the text by sliding to right. It can be used as a template for websites.

**Describe the solution you'd like**
It is built using HTML and CSS

**Comment by kiruba-r11** [comment]
@Ayush7614 I would like to work on this as a part of HCSSoC'21

**Comment by kiruba-r11** [comment]
@Ayush7614 Can i start working?

**Comment by Ayush7614** [comment]
Already we have
