### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by sejal1126** [Ayush7614/Bundli-Frontend#237]
I want to contribute registration form using html and css.
Please assign me this issue.

**Comment by Ayush7614** [comment]
under which program

**Comment by sejal1126** [comment]
DevIncept open source program

**Comment by Ankita297** [comment]
@sejal1126 go ahead .

**Comment by Ayush7614** [comment]
@sejal1126 what is status

**Comment by sejal1126** [comment]
yeah! It's in process.
