### ISSUE TITLE
Simon Game

### ISSUE THREAD

**Issue by Harikrishnaa3131** [Ayush7614/Bundli-Frontend#246]
## Aim

To create a simon game using HTML, CSS, Javascript.

## Description

- A Simon game created using HTML, CSS, Javascript.
- Simon is an electronic game of memory skill invented by Ralph H. Baer and Howard J. Morrison, working for toy design firm Marvin Glass and Associates with software programming by Lenny Cope. The device creates a series of tones and lights and requires a user to repeat the sequence. If the user succeeds, the series becomes progressively longer and more complex. Once the user fails or the time limit runs out, the game is over. 
- This is a wonderful and fun-filled memory game. 
I would like to contribute to this issue under HCSSoC.
@Ayush7614 Kindly assign me this issue.

**Comment by Ayush7614** [comment]
Already we have
