### ISSUE TITLE
Responsive Social Media Footer

### ISSUE THREAD

**Issue by pranjay-poddar** [Ayush7614/Bundli-Frontend#340]
Would like to work on adding a social media icon footer with animation in icons and responsive design.

Please assign this task to me under Hacktoberfest21.

**Comment by riyakushwaha** [comment]
Hii, Have you opened this issue for yourself and working on it?

**Comment by pranjay-poddar** [comment]
@riyakushwaha yes I've opened this issue and waiting for the project maintainer to assign this task to me after that I'll start working on this.
