### ISSUE TITLE
Creating a 3D digital card payment UI Prototype

### ISSUE THREAD

**Issue by NerdyVisky** [Ayush7614/Bundli-Frontend#351]
# Aim 
To design a credit/debit card payment front-end gateway with 3D card-flip and animations using open-source js libraries.

# Technologies to be used
HTML5, SASS, JS and JS libraries.

**Comment by Ayush7614** [comment]
Under which program you can contribute

**Comment by Ayush7614** [comment]
Already we have in the repo
