### ISSUE TITLE
Atomic Symbol Generator

### ISSUE THREAD

**Issue by yash22arora** [Ayush7614/Bundli-Frontend#352]
# Aim
To make a simple project using HTML, CSS, and Javascript to fetch info from a form and manipulate the data into a good-looking atomic symbol. It will encourage the use of javascript in static sites and also give rise to a cool output.

# Details

- The user would need to enter info like their Name, Age and Weight
- The input would be used to form a good looking atomic symbol 
- The weight will be treated as atomic weight and the age as atomic number
- Electronic configuration will also be displayed.

### sample photos:
![image](https://user-images.githubusercontent.com/72307157/135662256-769bebac-46c6-46fc-824e-197d348a20e7.png)

![image](https://user-images.githubusercontent.com/72307157/135662316-7d56527a-178d-493c-ace3-7981489bda41.png)

**Comment by Ayush7614** [comment]
Under which program you can contribute mention here

**Comment by yash22arora** [comment]
I want to contribute for the Hacktoberfest. I can create a new folder named Atomic Symbol Generator for this project.

**Comment by Ayush7614** [comment]
Go Ahead @yash22arora

**Comment by yash22arora** [comment]
Created a PR, Please review it and merge if it's okay! It would be great if you could also give the "hacktoberfest-accepted" label to the PR
