### ISSUE TITLE
Styled button with changes in cursor type

### ISSUE THREAD

**Issue by sushovanb02** [Ayush7614/Bundli-Frontend#353]
# Aim

- The button in age-calculator app is not visually appealing and the cursor type also remains the same. The aim is to make it appealing.

# Details

- I aim to add styling to the button as well change the cursor type to pointer

# Sample Photo
![image](https://user-images.githubusercontent.com/73771796/135664124-071eb50e-1777-49ba-8f69-fb738e9e35f6.png)

**Comment by sushovanb02** [comment]
@Ayush7614 please assign me this issue

**Comment by Ayush7614** [comment]
Under which Program

**Comment by sushovanb02** [comment]
> Under which Program

Hacktoberfest 2021

**Comment by sushovanb02** [comment]
@Ayush7614 This issue is for the Hacktoberfest 2021. Please add the labels.
