### ISSUE TITLE
Added Stop watch in JS

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Bundli-Frontend#4]

**Comment by ambalika24** [comment]
I can work on this issue. Please assign this to me.

**Comment by Ayush7614** [comment]
@ambalika24 under which program you have to work

**Comment by siddhi-244** [comment]
I would like to work on this under psoc !

**Comment by ambalika24** [comment]
> @ambalika24 under which program you have to work

I would like to work under PSoC.
