### ISSUE TITLE
BMI Calculator in JS

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Bundli-Frontend#5]

**Comment by shvam0000** [comment]
I would like to work on this app, thus I request you to assign this issue to me.

**Comment by aditpatel01** [comment]
Would like to work on adding a BMI Calculator to this project, therefore I request you to please assign this task to me.

**Comment by akshit-289** [comment]
Would like to work on this feature, thus I request you to assign this issue to me.

**Comment by Ayush7614** [comment]
Mention your program @shvam0000

**Comment by shvam0000** [comment]
Hack Club SOC @Ayush7614

**Comment by shvam0000** [comment]
@Ayush7614 we can use frontend libraries for the projects right?
