### ISSUE TITLE
Welcome to GirlScript Summer Of Code22

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Bundli-Frontend#520]
Hello, Everyone ✨, Hope you guys are doing fine! 🙌

Thanks for showing your interest in being a part of the GSSOC22(https://gssoc.girlscript.tech/) 💥

We are super delighted to have you on board for your Contributions in Bundli-Frontend(https://github.com/Ayush7614/Bundli-Frontend) 🙌

GirlScript Summer Of Code is a three-month-long Open-Source Program conducted every summer by the Girlscript Foundation. With constant efforts, participants contribute to numerous projects under the extreme guidance of skilled mentors over these months. With such exposure, students begin to contribute to real-world projects from the comfort of their homes. GirlScript Summer Of Code has witnessed active participation over the years, and the 2022 edition aims to carry the legacy with a promising impact.

**Comment by isha614** [comment]
Hey Ayush ! Can I add my  project which I created using HTML,CSS, JS.
So is it necessary to assign it?

**Comment by mahiiverse1** [comment]
@Ayush7614 Hey Ayush! I have a pre-made project that I have made using HTML, CSS and JS, So can I add a project like that here? Please let me know
