### ISSUE TITLE
Adding Weather App to the Project List: GSSOC Participant

### ISSUE THREAD

**Issue by AmolShelke2** [Ayush7614/Bundli-Frontend#521]
Hey, Project Admin I'm Amol Shelke GSSOC 2022 Contributor And I've come up with your project, and I find that this is what I was looking for because I have Experienced in frontEnd So I want to add my simple Weather app to the list as it is created by me with the good UI and some API. I hope you will go through my Issue and give a look at it. 
![weather png](https://user-images.githubusercontent.com/95171638/156001785-dc12b568-6e99-436d-b700-3f60742c9531.png)

**Comment by Ayush7614** [comment]
> Hey, Project Admin I'm Amol Shelke GSSOC 2022 Contributor And I've come up with your project, and I find that this is what I was looking for because I have Experienced in frontEnd So I want to add my simple Weather app to the list as it is created by me with the good UI and some API. I hope you will go through my Issue and give a look at it. ![weather png](https://user-images.githubusercontent.com/95171638/156001785-dc12b568-6e99-436d-b700-3f60742c9531.png)

@AmolShelke2 Thank You for your interest in the project
