### ISSUE TITLE
LinkedIn Clone : GSSoC Contributor

### ISSUE THREAD

**Issue by Rajdip019** [Ayush7614/Bundli-Frontend#523]
I have created  a full stack LinkedIn  Clone. Can I add that?

Here is a link:  https://linkedin-clone-rajdeep019.vercel.app/

**Comment by Ayush7614** [comment]
@Rajdip019 Thank You for your interest in the project can you tell me you can do this under gssoc22 and if you are gssoc22 participant then please mention this from next issue

**Comment by Rajdip019** [comment]
Yes I am a GSSoC participant. And thankyou for assigning.

**Comment by Ayush7614** [comment]
> Yes I am a GSSoC participant. And thankyou for assigning.

@Rajdip019 Go Ahead

**Comment by sahilsaini110** [comment]
@Rajdip019 are you still working on this. if no I would like to work on this.
