### ISSUE TITLE
Please add some Responsive Navbar designs.

### ISSUE THREAD

**Issue by pratham-ops** [Ayush7614/Bundli-Frontend#527]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sulogna2001** [comment]
Hey Can I work  on  this issue under GSSOC22

**Comment by pratham-ops** [comment]
> Hey Can I work on this issue under GSSOC22

Go ahead you can start working on it 👍

**Comment by Ayush7614** [comment]
Not Needed Already there are many templates of responsive navbar designs
