### ISSUE TITLE
Facebook Login Page Clone : GSSoC'22 contributor

### ISSUE THREAD

**Issue by Susmita-Dey** [Ayush7614/Bundli-Frontend#529]
**I'm a GSSoC'22 contributor.**
I have created a Facebook Login Page Clone Using Tailwind. Can I add that?

Here is a demo link to the project : https://susmita-dey.github.io/Facebook-Login-Page-Clone-Tailwind-CSS/

**Comment by Ayush7614** [comment]
Go Ahead @Susmita-Dey

**Comment by Susmita-Dey** [comment]
Thanks for assigning it to me.
