### ISSUE TITLE
A new project named as Sticky Notes

### ISSUE THREAD

**Issue by isha614** [Ayush7614/Bundli-Frontend#531]
You can check the live demo here. [https://sticky-notes01.netlify.app/](url)

**Comment by sulogna2001** [comment]
Hey Can I work  on  this issue under GSSOC22

**Comment by isha614** [comment]
> Hey Can I work on this issue under GSSOC22

I want to work that's why I created an issue to get assigned to me

**Comment by Ayush7614** [comment]
#530
