### ISSUE TITLE
A new Project named Guess My Number

### ISSUE THREAD

**Issue by ZeyadTarekk** [Ayush7614/Bundli-Frontend#538]
The idea of the game is that you start by guessing a number from 1 to 20 if you guessed wrong the score decreases and the first time you guess the right number this becomes your high score then you can hit again to play again and if you get a higher score your high score gets updated.
Using HTML, CSS, JavaScript

**Comment by Ayush7614** [comment]
Go Ahead @ZeyadTarekk
