### ISSUE TITLE
Instagram web home landing page

### ISSUE THREAD

**Issue by dewanshiPaul** [Ayush7614/Bundli-Frontend#602]
# Aim

Instagram web landing page clone using react js

# screenshot

![image](https://user-images.githubusercontent.com/92020810/161366728-915b635a-b76d-4971-a40b-b99aa05484e3.png)
![image](https://user-images.githubusercontent.com/92020810/161366734-795417ae-3cf6-40a7-a306-b51fdbacb50e.png)

I am gssoc'22 participant. Kindly review it and assign me.

**Comment by Ayush7614** [comment]
Already we have
