### ISSUE TITLE
Add file uploader

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Ayush7614/Bundli-Frontend#622]
I will be a file uploading system that users can easily upload files and drag ,drop features will be added here.

Tech stack:
<li>Html5</li>
<li>Css</li>
<li>Javascript</li>
<br/>

- [x] I am a gssoc'22 contributor. Please assign me this Issue.

**Comment by gurjeetsinghvirdee** [comment]
assigned you @Sulagna-Dutta-Roy
