### ISSUE TITLE
Add Youtube Clone

### ISSUE THREAD

**Issue by 19arnab190201** [Ayush7614/Bundli-Frontend#628]
I want to add a youtube clone. please  assign it to me under gssoc22

Tech used

React
MUI
HTML
CSS
JS

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @19arnab190201

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue ? Then assign me @gurjeetsinghvirdee @Ayush7614

**Comment by gurjeetsinghvirdee** [comment]
> Can I work on this Issue ? Then assign me @gurjeetsinghvirdee @Ayush7614 

Assigned

**Comment by Sulagna-Dutta-Roy** [comment]
Can I add this project without React ??? Because I will use Pure JS and youtube apis if applicable.
