### ISSUE TITLE
Submit response Popup button

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Ayush7614/Bundli-Frontend#633]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is a Submit response Popup button.

### The idea behind this project :
This is just like when we submit our response then a popup arises for confirmation.

### How does it work
Here we have a submit button that will preview when you will click on submit button then thanks popup confirmation button will be popup out from the top.

for more details please refer to this attached images.
![Screenshot (118)](https://user-images.githubusercontent.com/73521123/163581066-55bb49cd-44c3-46e7-9185-984d9e4d2adc.png)
![Screenshot (119)](https://user-images.githubusercontent.com/73521123/163581149-28e13adb-f522-45ec-b4c3-aa3ba1a6782e.png)

**Comment by Ayush7614** [comment]
Already we have
