### ISSUE TITLE
I want to add a responsive landing Page created with HTML CSS and JavaScript.

### ISSUE THREAD

**Issue by AmolShelke2** [Ayush7614/Bundli-Frontend#639]
**Is your feature request related to a problem? Please describe.**

Hey project admin I'm a GSSOC participant and I want to add my responsive landing page created with HTML CSS and JavaScript with animations and a responsive hamburger menu I hope that you will go through my ISSUE and assign me this issue to work on.

**Describe the solution you'd like**
I'm attaching the DEMO below please give it a look..

**Describe alternatives you've considered**
I am also giving the deployment link you can visit it..
[Responsive landing page](https://responsive-web-design-nu.vercel.app/)

**Additional context**
![responsiveWeb png](https://user-images.githubusercontent.com/95171638/163671081-be7071e4-deaf-4e21-b565-3b461819ea3c.png)

@gurjeetsinghvirdee kindly review this issue

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @AmolShelke2
