### ISSUE TITLE
Adding An Dynamic Login page

### ISSUE THREAD

**Issue by SamarthKadam** [Ayush7614/Bundli-Frontend#650]
Can I add this Project which is dynamic Login pages build using React? Once logged in even if you reload the page You will be still logged in. And it is also responsive. Below is the image of the project
![Screenshot (156)](https://user-images.githubusercontent.com/87573175/163940114-ee19fdd3-f27d-4375-b6a2-6fed981c9c20.png)

**Comment by Ayush7614** [comment]
Already we have
