### ISSUE TITLE
Create a SNRKS Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [Ayush7614/Bundli-Frontend#655]
**Is your feature request related to a problem? Please describe.**
This would be a Website UI Clone

**Describe the solution you'd like**
I will use HTML, CSS, JS and Bootstrap Frame-work

**Describe alternatives you've considered**
No Alternative

**Additional context**
![image](https://user-images.githubusercontent.com/76027425/164409148-90512898-ab21-438c-abe9-f9c889484664.png)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Kumar-laxmi
