### ISSUE TITLE
Add a Chrome Extension Downloading website

### ISSUE THREAD

**Issue by mahiiverse1** [Ayush7614/Bundli-Frontend#656]
**Is your feature request related to a problem? Please describe.**
I want to add a website that looks like it's promoting a certain productivity Chrome Extension and users can download the Chrome Extension from that website. 

**Describe the solution you'd like**
The Website will be the main promoting page for a Productivity Timer Chrome extension. It will have a Download feature as well as the website will show the features of the extension, public reviews, no of downloads, etc. Just front end of the website, no backend implementation

**Describe alternatives you've considered**
I will mostly be using React to create the website.

Kindly assign this issue to me if you would like me to work on it!

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @mahiiverse1
