### ISSUE TITLE
Hotstar Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Ayush7614/Bundli-Frontend#657]
**Project title**
Hotstar Website Clone

**Description**
It's an OTT platform where we can enjoy movies,cricket and many more
**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

**Comment by SupriyaGembali** [comment]
Please assign this issue to me @Ayush7614

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @SupriyaGembali
