### ISSUE TITLE
Walmart Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [Ayush7614/Bundli-Frontend#658]
**Project title**
Walmart Website  Clone

**Description**
Walmart is an Multinational E-commerce Website

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

**Comment by SupriyaGembali** [comment]
@Ayush7614 please assign this to me sir

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @SupriyaGembali
