### ISSUE TITLE
I want to add a jumping square project to the current repository.

### ISSUE THREAD

**Issue by AmolShelke2** [Ayush7614/Bundli-Frontend#659]
**Is your feature request related to a problem? Please describe.**
No, my issue is not requested to a related problem

**Describe the solution you'd like**
Hey project admin I'm a GSSOC participant and I have come up with your project I will add a jumping square project created with HTML And CSS it consists of animations and transitions it is very useful for beginners who don't have the idea of working with CSS transitions I hope that you will go through my issue and assign me this issue to work on.

**Additional context**

https://user-images.githubusercontent.com/95171638/164912191-9ca7392c-afba-4907-b164-975dbf633d67.mp4

@gurjeetsinghvirdee kindly review this isssue.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @AmolShelke2
