### ISSUE TITLE
Add Picture Puzzle Game

### ISSUE THREAD

**Issue by BabyElias** [Ayush7614/Bundli-Frontend#662]
I would like to add a simple drag-and-drop picture puzzle game made using HTML,CSS & JS to the repo.
A demo is attached as below.Please assign me this under GSSoC'22

https://user-images.githubusercontent.com/95405559/164966040-9775f7a6-3507-4d3d-8dcc-e39028bf7c7c.mp4

**Comment by Ayush7614** [comment]
Already we have
