### ISSUE TITLE
I will add a ball animation project to the Bundii-frontend repository.

### ISSUE THREAD

**Issue by AmolShelke2** [Ayush7614/Bundli-Frontend#686]
**Is your feature request related to a problem? Please describe.**
no my, my feature is not a request related to a problem.

**Describe the solution you'd like**
Hello project admin I'm a GSSOC participant and I want to add my ball animation project to the bundl frontend project created with HTML and CSS please go through the demo that I attached below and assign me this issue to work on.

**Describe alternatives you've considered**
No, I have not considered any alternatives.

**Additional context**

https://user-images.githubusercontent.com/95171638/166119204-3a38597a-a00b-4cf1-be15-660f8b5e8bcb.mp4

@gurjeetsinghvirdee kindly review this issue.

**Comment by gurjeetsinghvirdee** [comment]
you are copying others project 
https://www.youtube.com/watch?v=NQTij24ILrY
