### ISSUE TITLE
KickMate

### ISSUE THREAD

**Issue by dasgupta002** [Ayush7614/Bundli-Frontend#698]
**Is your feature request related to a problem? Please describe.**

A website for football geeks, where one can search, follow up and enjoy loads of match videos from his favorite teams with a funny UI and interactive space.

**Describe the solution you'd like**

The data comes from a third party REST endpoint and the UI is designed with React and simple CSS.

**Additional context**

As a contributor to GSSOC '22, I myself am keen to implement this idea.

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @dasgupta002
