### ISSUE TITLE
Youtube Player

### ISSUE THREAD

**Issue by SamarthKadam** [Ayush7614/Bundli-Frontend#716]
Can I add this Youtube player which implements the functionality of youtube like
1>play pause
2>Forward/Reverse
3>Full screen
With Animations
 UI is All from the youtube?
This would be little complex project. Let me know If I am getting this assigned as level 3 then I will be  working on it
What are your thoughts on this? Let me know
Thank you

**Comment by Ayush7614** [comment]
Issue was already open by someone else
