### ISSUE TITLE
Vertical Image sliders

### ISSUE THREAD

**Issue by RAHULBAWA777** [Ayush7614/Bundli-Frontend#717]
Vertical image sliders using html css and js

**Comment by void-ness** [comment]
I intend to utilise the display property of CSS and initially set all the slider elements display to none using js. then for selective elements we can make the property visible and add transform properties to give the vertical slider the desired look. kindly assign me the issue and I intend to work on it. thanks

**Comment by AmolShelke2** [comment]
@gurjeetsinghvirdee bhai ye project copied nhi hai ky. 
https://www.youtube.com/watch?v=laNpbZISwjY

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee bhai ye project copied nhi hai ky. 
> https://www.youtube.com/watch?v=laNpbZISwjY

Ye toh bas issue hai code aane par pta chlega

**Comment by AmolShelke2** [comment]
Bhai aap naye issues assign krre ho purane issues ko ignore krre.
