### ISSUE TITLE
Interactive Tic Tac Toe game

### ISSUE THREAD

**Issue by void-ness** [Ayush7614/Bundli-Frontend#718]
**Is your feature request related to a problem? Please describe.**
An interactive Tic-Tac-Toe game. Through this I am planning to create an interactive tic tac toe game which will include the following functionalities-
1. score tracker for both the players.
2. allows user to select team names.
3. allows user to customize the BG of their game by selecting a randomly generated color.
4. using media queries in js, to play different winning animations on website and phone

**Describe the solution you'd like**
I intend to make the above proposed game, with a well documented code. my tech stack will include HTML, CSS and JS.

**Comment by Ayush7614** [comment]
Already we have
