### ISSUE TITLE
CS Quiz App in React & Typescript

### ISSUE THREAD

**Issue by piyusha2001** [Ayush7614/Bundli-Frontend#775]
**Is your feature request related to a problem? Please describe.**
I want to make a quiz app containing fun computer science questions for developers and any computer science enthusiast.

**Describe the solution you'd like**
I am going to make it using React ,typescript and Open Trivia DB API.
Please assign me this issue under GSSoC'22.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u
