### ISSUE TITLE
Currency Converter in JS

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Bundli-Frontend#9]

**Comment by shvam0000** [comment]
I would like to work on this issue, thus I request you to assign this to me.

**Comment by Ayush7614** [comment]
Under which program

**Comment by shvam0000** [comment]
Hack Club SOC

**Comment by Ayush7614** [comment]
What is the Progress @shvam0000

**Comment by Ayush7614** [comment]
It has been 24 days
